# if undefined it'll ask upon start

# amount of packets sent on join
PACKETS: 99999
# delay between packets
DELAY: 0
ACCOUNT: "MinecraftOMG"
CLIENT_AMOUNT: 5
#TARGET:
#  # target ip
#  HOST: "asdasdsad"
#  # target port
#  PORT: 25565
#  # target realmID
#  REALM_ID: 0
#  # target realm invite
#  REALM_INVITE: "asdasdasd"

